### PR TITLE
Fix type error and pylint

### LINKED ISSUE #2: Incompatible type error from tensorflow2.0/example/main.py
I had trained the fashion-mnist model into GCS and deployed the GCF.

However, the function crashed due to this error:
> Incompatible type conversion requested to type 'float64' for variable of type 'float32'

```python
  ...
  File "/user_code/main.py", line 22, in call
    x = self.conv1(x)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 196, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1078, in __call__
    return self.conv_op(inp, filter)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 634, in __call__
    return self.call(inp, filter)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 233, in __call__
    name=self.name)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1123, in conv2d_eager_fallback
    _attr_T, _inputs_T = _execute.args_to_matching_eager([input, filter], _ctx)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 202, in args_to_matching_eager
    ret = [internal_convert_to_tensor(t, dtype, ctx=ctx) for t in l]
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 202, in <listcomp>
    ret = [internal_convert_to_tensor(t, dtype, ctx=ctx) for t in l]
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1420, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/env/local/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1371, in _dense_var_to_tensor
    "of type {!r}".format(dtype.name, self.dtype.name))
ValueError: Incompatible type conversion requested to type 'float64' for variable of type 'float32'
```

### PR DESCRIPTION
**Pull request by northtree**
Closes #2 

BTW, I used `yapf` to format the code to fix ident issue and also fix some `pylint`.

I suggest to remove the `source` and `pack.zip` since there is no need to deploy TF2 for Google Cloud Functions python3.7 runtime.

### CODE REVIEW

**Review by ryfeus — APPROVED** [review]
Looks great. Approved. Thank you for help.

**Comment by northtree** [comment]
No worries. Let me know if need any changes before merge. 

BTW, I wonder if we need one GCF example which could predict any online image.

**Comment by ryfeus** [comment]
@northtree thanks. No changes needed, feel free to merge. I think I have implementation for downloading online image in AWS Lambda repo (https://github.com/ryfeus/lambda-packs/blob/master/Tensorflow/index.py#L148), but not in GCF one so feel free to make a PR.

**Comment by northtree** [comment]
@ryfeus I don't have _write access_ to merge PR for this repo. Maybe only you could merge.

**Comment by northtree** [comment]
@ryfeus Do you suggest ^^ that we could have one GCF to download online image and predict its `fashion-mnist` category?

**Comment by ryfeus** [comment]
@northtree that is a possibility, though with fashion mnist it may be an issue that it may not be effective at predicting non fashion mnist images. In the example I've shared before the model in question was Inception-v3 which worked on a lot of different images.

**Pull request merged**
